# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppendPeriod.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AppendPeriod(object):
    def setupUi(self, AppendPeriod):
        AppendPeriod.setObjectName("AppendPeriod")
        AppendPeriod.resize(280, 520)
        self.Append = QtWidgets.QPushButton(AppendPeriod)
        self.Append.setGeometry(QtCore.QRect(10, 10, 260, 28))
        self.Append.setObjectName("Append")
        self.Projects = QtWidgets.QComboBox(AppendPeriod)
        self.Projects.setGeometry(QtCore.QRect(10, 90, 260, 28))
        self.Projects.setEditable(True)
        self.Projects.setObjectName("Projects")
        self.Tasks = QtWidgets.QComboBox(AppendPeriod)
        self.Tasks.setGeometry(QtCore.QRect(10, 118, 260, 28))
        self.Tasks.setEditable(True)
        self.Tasks.setObjectName("Tasks")
        self.Events = QtWidgets.QComboBox(AppendPeriod)
        self.Events.setGeometry(QtCore.QRect(10, 146, 260, 28))
        self.Events.setEditable(True)
        self.Events.setObjectName("Events")
        self.Name = QtWidgets.QLineEdit(AppendPeriod)
        self.Name.setGeometry(QtCore.QRect(10, 190, 260, 28))
        self.Name.setObjectName("Name")
        self.StartLabel = QtWidgets.QLabel(AppendPeriod)
        self.StartLabel.setGeometry(QtCore.QRect(10, 230, 60, 28))
        self.StartLabel.setObjectName("StartLabel")
        self.StartTime = QtWidgets.QDateTimeEdit(AppendPeriod)
        self.StartTime.setGeometry(QtCore.QRect(70, 230, 200, 28))
        self.StartTime.setObjectName("StartTime")
        self.FinishLabel = QtWidgets.QLabel(AppendPeriod)
        self.FinishLabel.setGeometry(QtCore.QRect(10, 270, 60, 28))
        self.FinishLabel.setObjectName("FinishLabel")
        self.FinishTime = QtWidgets.QDateTimeEdit(AppendPeriod)
        self.FinishTime.setGeometry(QtCore.QRect(70, 270, 200, 28))
        self.FinishTime.setObjectName("FinishTime")
        self.Note = QtWidgets.QTextEdit(AppendPeriod)
        self.Note.setGeometry(QtCore.QRect(10, 310, 260, 200))
        self.Note.setObjectName("Note")
        self.OpenEditor = QtWidgets.QCheckBox(AppendPeriod)
        self.OpenEditor.setGeometry(QtCore.QRect(10, 50, 260, 28))
        self.OpenEditor.setChecked(True)
        self.OpenEditor.setObjectName("OpenEditor")

        self.retranslateUi(AppendPeriod)
        self.Append.clicked.connect(AppendPeriod.AppendPeriod)
        self.Projects.currentIndexChanged['int'].connect(AppendPeriod.ProjectsChanged)
        self.Tasks.currentIndexChanged['int'].connect(AppendPeriod.TasksChanged)
        self.Events.currentIndexChanged['int'].connect(AppendPeriod.EventsChanged)
        self.Name.editingFinished.connect(AppendPeriod.NameChanged)
        self.StartTime.dateTimeChanged['QDateTime'].connect(AppendPeriod.StartTimeChanged)
        self.FinishTime.dateTimeChanged['QDateTime'].connect(AppendPeriod.FinishTimeChanged)
        self.Note.textChanged.connect(AppendPeriod.NoteChanged)
        QtCore.QMetaObject.connectSlotsByName(AppendPeriod)

    def retranslateUi(self, AppendPeriod):
        _translate = QtCore.QCoreApplication.translate
        AppendPeriod.setWindowTitle(_translate("AppendPeriod", "新增時段"))
        AppendPeriod.setToolTip(_translate("AppendPeriod", "新增時段"))
        AppendPeriod.setStatusTip(_translate("AppendPeriod", "新增時段"))
        AppendPeriod.setWhatsThis(_translate("AppendPeriod", "新增時段"))
        self.Append.setToolTip(_translate("AppendPeriod", "快速新增時段"))
        self.Append.setStatusTip(_translate("AppendPeriod", "快速新增時段"))
        self.Append.setWhatsThis(_translate("AppendPeriod", "快速新增時段"))
        self.Append.setText(_translate("AppendPeriod", "新增時段"))
        self.Projects.setToolTip(_translate("AppendPeriod", "計畫列表"))
        self.Projects.setStatusTip(_translate("AppendPeriod", "計畫列表"))
        self.Projects.setWhatsThis(_translate("AppendPeriod", "計畫列表"))
        self.Tasks.setToolTip(_translate("AppendPeriod", "任務列表"))
        self.Tasks.setStatusTip(_translate("AppendPeriod", "任務列表"))
        self.Tasks.setWhatsThis(_translate("AppendPeriod", "任務列表"))
        self.Events.setToolTip(_translate("AppendPeriod", "事件列表"))
        self.Events.setStatusTip(_translate("AppendPeriod", "事件列表"))
        self.Events.setWhatsThis(_translate("AppendPeriod", "事件列表"))
        self.Name.setPlaceholderText(_translate("AppendPeriod", "時段名稱"))
        self.StartLabel.setText(_translate("AppendPeriod", "開始："))
        self.StartTime.setToolTip(_translate("AppendPeriod", "時段開始時間"))
        self.StartTime.setStatusTip(_translate("AppendPeriod", "時段開始時間"))
        self.StartTime.setWhatsThis(_translate("AppendPeriod", "時段開始時間"))
        self.StartTime.setDisplayFormat(_translate("AppendPeriod", "yyyy/MM/dd hh:mm:ss"))
        self.FinishLabel.setText(_translate("AppendPeriod", "結束："))
        self.FinishTime.setToolTip(_translate("AppendPeriod", "時段結束時間"))
        self.FinishTime.setStatusTip(_translate("AppendPeriod", "時段結束時間"))
        self.FinishTime.setWhatsThis(_translate("AppendPeriod", "時段結束時間"))
        self.FinishTime.setDisplayFormat(_translate("AppendPeriod", "yyyy/MM/dd hh:mm:ss"))
        self.Note.setPlaceholderText(_translate("AppendPeriod", "內容描述"))
        self.OpenEditor.setToolTip(_translate("AppendPeriod", "新增後打開時段編輯器"))
        self.OpenEditor.setStatusTip(_translate("AppendPeriod", "新增後打開時段編輯器"))
        self.OpenEditor.setWhatsThis(_translate("AppendPeriod", "新增後打開時段編輯器"))
        self.OpenEditor.setText(_translate("AppendPeriod", "打開時段編輯器"))
