# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PeriodEditorUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PeriodEditorUI(object):
    def setupUi(self, PeriodEditorUI):
        PeriodEditorUI.setObjectName("PeriodEditorUI")
        PeriodEditorUI.resize(640, 480)
        PeriodEditorUI.setMinimumSize(QtCore.QSize(640, 480))
        PeriodEditorUI.setMaximumSize(QtCore.QSize(640, 480))
        self.NameLabel = QtWidgets.QLabel(PeriodEditorUI)
        self.NameLabel.setGeometry(QtCore.QRect(20, 20, 100, 28))
        self.NameLabel.setObjectName("NameLabel")
        self.NameEditor = QtWidgets.QLineEdit(PeriodEditorUI)
        self.NameEditor.setGeometry(QtCore.QRect(120, 20, 500, 28))
        self.NameEditor.setAutoFillBackground(False)
        self.NameEditor.setFrame(True)
        self.NameEditor.setObjectName("NameEditor")
        self.TypeLabel = QtWidgets.QLabel(PeriodEditorUI)
        self.TypeLabel.setGeometry(QtCore.QRect(20, 60, 100, 28))
        self.TypeLabel.setObjectName("TypeLabel")
        self.TypeBox = QtWidgets.QComboBox(PeriodEditorUI)
        self.TypeBox.setGeometry(QtCore.QRect(120, 60, 120, 28))
        self.TypeBox.setEditable(False)
        self.TypeBox.setObjectName("TypeBox")
        self.UsageLabel = QtWidgets.QLabel(PeriodEditorUI)
        self.UsageLabel.setGeometry(QtCore.QRect(250, 60, 80, 28))
        self.UsageLabel.setObjectName("UsageLabel")
        self.UsageBox = QtWidgets.QComboBox(PeriodEditorUI)
        self.UsageBox.setGeometry(QtCore.QRect(330, 60, 100, 28))
        self.UsageBox.setObjectName("UsageBox")
        self.TimeZoneLabel = QtWidgets.QLabel(PeriodEditorUI)
        self.TimeZoneLabel.setGeometry(QtCore.QRect(440, 60, 60, 28))
        self.TimeZoneLabel.setObjectName("TimeZoneLabel")
        self.TimeZoneBox = QtWidgets.QComboBox(PeriodEditorUI)
        self.TimeZoneBox.setGeometry(QtCore.QRect(500, 60, 120, 28))
        self.TimeZoneBox.setEditable(True)
        self.TimeZoneBox.setObjectName("TimeZoneBox")
        self.StartLabel = QtWidgets.QLabel(PeriodEditorUI)
        self.StartLabel.setGeometry(QtCore.QRect(20, 100, 100, 28))
        self.StartLabel.setObjectName("StartLabel")
        self.StartTime = QtWidgets.QDateTimeEdit(PeriodEditorUI)
        self.StartTime.setGeometry(QtCore.QRect(120, 100, 240, 28))
        self.StartTime.setCalendarPopup(True)
        self.StartTime.setObjectName("StartTime")
        self.FinishLabel = QtWidgets.QLabel(PeriodEditorUI)
        self.FinishLabel.setGeometry(QtCore.QRect(20, 140, 100, 28))
        self.FinishLabel.setObjectName("FinishLabel")
        self.FinishTime = QtWidgets.QDateTimeEdit(PeriodEditorUI)
        self.FinishTime.setGeometry(QtCore.QRect(120, 140, 240, 28))
        self.FinishTime.setCalendarPopup(True)
        self.FinishTime.setObjectName("FinishTime")
        self.ItemLabel = QtWidgets.QLabel(PeriodEditorUI)
        self.ItemLabel.setGeometry(QtCore.QRect(370, 100, 80, 28))
        self.ItemLabel.setObjectName("ItemLabel")
        self.ItemSpin = QtWidgets.QSpinBox(PeriodEditorUI)
        self.ItemSpin.setGeometry(QtCore.QRect(450, 100, 170, 28))
        self.ItemSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ItemSpin.setMaximum(999999999)
        self.ItemSpin.setProperty("value", 196833)
        self.ItemSpin.setObjectName("ItemSpin")
        self.StatesLabel = QtWidgets.QLabel(PeriodEditorUI)
        self.StatesLabel.setGeometry(QtCore.QRect(370, 140, 80, 28))
        self.StatesLabel.setObjectName("StatesLabel")
        self.StatesBox = QtWidgets.QComboBox(PeriodEditorUI)
        self.StatesBox.setGeometry(QtCore.QRect(450, 140, 170, 28))
        self.StatesBox.setObjectName("StatesBox")
        self.NoteLabel = QtWidgets.QLabel(PeriodEditorUI)
        self.NoteLabel.setGeometry(QtCore.QRect(20, 180, 100, 28))
        self.NoteLabel.setObjectName("NoteLabel")
        self.NoteEdit = QtWidgets.QTextEdit(PeriodEditorUI)
        self.NoteEdit.setGeometry(QtCore.QRect(120, 180, 500, 160))
        self.NoteEdit.setObjectName("NoteEdit")
        self.FirstLine = QtWidgets.QFrame(PeriodEditorUI)
        self.FirstLine.setGeometry(QtCore.QRect(20, 350, 600, 3))
        self.FirstLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.FirstLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FirstLine.setObjectName("FirstLine")
        self.Append = QtWidgets.QPushButton(PeriodEditorUI)
        self.Append.setGeometry(QtCore.QRect(20, 310, 80, 28))
        self.Append.setObjectName("Append")
        self.AppleLabel = QtWidgets.QLabel(PeriodEditorUI)
        self.AppleLabel.setGeometry(QtCore.QRect(20, 360, 100, 28))
        self.AppleLabel.setObjectName("AppleLabel")
        self.comboBox = QtWidgets.QComboBox(PeriodEditorUI)
        self.comboBox.setGeometry(QtCore.QRect(120, 360, 500, 28))
        self.comboBox.setObjectName("comboBox")
        self.EventLabel = QtWidgets.QLabel(PeriodEditorUI)
        self.EventLabel.setGeometry(QtCore.QRect(20, 400, 100, 28))
        self.EventLabel.setObjectName("EventLabel")
        self.EventEdit = QtWidgets.QLineEdit(PeriodEditorUI)
        self.EventEdit.setGeometry(QtCore.QRect(120, 400, 500, 28))
        self.EventEdit.setReadOnly(True)
        self.EventEdit.setObjectName("EventEdit")
        self.SyncApple = QtWidgets.QPushButton(PeriodEditorUI)
        self.SyncApple.setGeometry(QtCore.QRect(500, 440, 120, 28))
        self.SyncApple.setObjectName("SyncApple")

        self.retranslateUi(PeriodEditorUI)
        QtCore.QMetaObject.connectSlotsByName(PeriodEditorUI)

    def retranslateUi(self, PeriodEditorUI):
        _translate = QtCore.QCoreApplication.translate
        PeriodEditorUI.setWindowTitle(_translate("PeriodEditorUI", "工作時段編輯器"))
        PeriodEditorUI.setToolTip(_translate("PeriodEditorUI", "工作時段編輯器"))
        PeriodEditorUI.setStatusTip(_translate("PeriodEditorUI", "工作時段編輯器"))
        PeriodEditorUI.setWhatsThis(_translate("PeriodEditorUI", "工作時段編輯器"))
        self.NameLabel.setText(_translate("PeriodEditorUI", "工時內容簡述："))
        self.TypeLabel.setText(_translate("PeriodEditorUI", "時段類型："))
        self.UsageLabel.setText(_translate("PeriodEditorUI", "啟用狀態："))
        self.TimeZoneLabel.setText(_translate("PeriodEditorUI", "時區："))
        self.StartLabel.setText(_translate("PeriodEditorUI", "開始時間："))
        self.StartTime.setDisplayFormat(_translate("PeriodEditorUI", "yyyy/MM/dd HH:mm:ss"))
        self.FinishLabel.setText(_translate("PeriodEditorUI", "結束時間："))
        self.FinishTime.setDisplayFormat(_translate("PeriodEditorUI", "yyyy/MM/dd HH:mm:ss"))
        self.ItemLabel.setText(_translate("PeriodEditorUI", "使用種類："))
        self.StatesLabel.setText(_translate("PeriodEditorUI", "時段狀態："))
        self.NoteLabel.setText(_translate("PeriodEditorUI", "詳細內容："))
        self.Append.setText(_translate("PeriodEditorUI", "新增"))
        self.AppleLabel.setText(_translate("PeriodEditorUI", "蘋果行事曆："))
        self.EventLabel.setText(_translate("PeriodEditorUI", "事件編號："))
        self.SyncApple.setText(_translate("PeriodEditorUI", "同步蘋果行事曆"))
