# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VtkModelPadUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VtkModelPadUi(object):
    def setupUi(self, VtkModelPadUi):
        VtkModelPadUi.setObjectName("VtkModelPadUi")
        VtkModelPadUi.resize(320, 640)
        self.ToolBox = QtWidgets.QToolBox()
        self.ToolBox.setObjectName("ToolBox")
        self.Camera = QtWidgets.QScrollArea()
        self.Camera.setGeometry(QtCore.QRect(0, 0, 320, 580))
        self.Camera.setObjectName("Camera")
        self.ToolBox.addItem(self.Camera, "")
        self.Actors = QtWidgets.QScrollArea()
        self.Actors.setGeometry(QtCore.QRect(0, 0, 320, 580))
        self.Actors.setObjectName("Actors")
        self.ToolBox.addItem(self.Actors, "")
        VtkModelPadUi.addWidget(self.ToolBox)
        self.CameraTemplate = QtWidgets.QWidget()
        self.CameraTemplate.setObjectName("CameraTemplate")
        self.TrackCamera = QtWidgets.QCheckBox(self.CameraTemplate)
        self.TrackCamera.setGeometry(QtCore.QRect(10, 10, 300, 24))
        self.TrackCamera.setChecked(True)
        self.TrackCamera.setObjectName("TrackCamera")
        self.PositionLine = QtWidgets.QFrame(self.CameraTemplate)
        self.PositionLine.setGeometry(QtCore.QRect(10, 40, 300, 3))
        self.PositionLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.PositionLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PositionLine.setObjectName("PositionLine")
        self.PositionLabel = QtWidgets.QLabel(self.CameraTemplate)
        self.PositionLabel.setGeometry(QtCore.QRect(10, 50, 300, 24))
        self.PositionLabel.setObjectName("PositionLabel")
        self.PositionXLabel = QtWidgets.QLabel(self.CameraTemplate)
        self.PositionXLabel.setGeometry(QtCore.QRect(10, 80, 30, 24))
        self.PositionXLabel.setObjectName("PositionXLabel")
        self.PositionX = QtWidgets.QDoubleSpinBox(self.CameraTemplate)
        self.PositionX.setGeometry(QtCore.QRect(40, 80, 270, 24))
        self.PositionX.setObjectName("PositionX")
        self.PositionYLabel = QtWidgets.QLabel(self.CameraTemplate)
        self.PositionYLabel.setGeometry(QtCore.QRect(10, 110, 30, 24))
        self.PositionYLabel.setObjectName("PositionYLabel")
        self.PositionY = QtWidgets.QDoubleSpinBox(self.CameraTemplate)
        self.PositionY.setGeometry(QtCore.QRect(40, 110, 270, 24))
        self.PositionY.setObjectName("PositionY")
        self.PositionZLabel = QtWidgets.QLabel(self.CameraTemplate)
        self.PositionZLabel.setGeometry(QtCore.QRect(10, 140, 30, 24))
        self.PositionZLabel.setObjectName("PositionZLabel")
        self.PositionZ = QtWidgets.QDoubleSpinBox(self.CameraTemplate)
        self.PositionZ.setGeometry(QtCore.QRect(40, 140, 270, 24))
        self.PositionZ.setObjectName("PositionZ")
        VtkModelPadUi.addWidget(self.CameraTemplate)
        self.ActorsTemplate = QtWidgets.QWidget()
        self.ActorsTemplate.setObjectName("ActorsTemplate")
        self.ActorsBox = QtWidgets.QComboBox(self.ActorsTemplate)
        self.ActorsBox.setGeometry(QtCore.QRect(0, 0, 320, 24))
        self.ActorsBox.setObjectName("ActorsBox")
        VtkModelPadUi.addWidget(self.ActorsTemplate)

        self.retranslateUi(VtkModelPadUi)
        VtkModelPadUi.setCurrentIndex(0)
        self.ToolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VtkModelPadUi)

    def retranslateUi(self, VtkModelPadUi):
        _translate = QtCore.QCoreApplication.translate
        VtkModelPadUi.setWindowTitle(_translate("VtkModelPadUi", "三維模型控制板"))
        VtkModelPadUi.setToolTip(_translate("VtkModelPadUi", "三維模型控制板"))
        VtkModelPadUi.setStatusTip(_translate("VtkModelPadUi", "三維模型控制板"))
        VtkModelPadUi.setWhatsThis(_translate("VtkModelPadUi", "三維模型控制板"))
        self.ToolBox.setItemText(self.ToolBox.indexOf(self.Camera), _translate("VtkModelPadUi", "場景相機"))
        self.ToolBox.setItemText(self.ToolBox.indexOf(self.Actors), _translate("VtkModelPadUi", "場景物件"))
        self.TrackCamera.setText(_translate("VtkModelPadUi", "及時更新相機參數"))
        self.PositionLabel.setText(_translate("VtkModelPadUi", "相機位置"))
        self.PositionXLabel.setText(_translate("VtkModelPadUi", "X : "))
        self.PositionYLabel.setText(_translate("VtkModelPadUi", "Y : "))
        self.PositionZLabel.setText(_translate("VtkModelPadUi", "Z : "))
